<template>
  <div id="create-expense">
    <h1>Add a Expense</h1>

    <form @submit.prevent="handleSubmit">
      <div class="form-group">
        <label for="description">description</label>
        <input
          type="text"
          :class="{ 'form-input-error': $v.expense.description.$error }"
          id="description"
          data-test="form-description-input"
          v-model="$v.expense.description.$model"
        />
        <div v-if="$v.expense.description.$error">
          <div
            class="form-feedback-error"
            v-if="!$v.expense.description.required"
          >Expense description is required.</div>
        </div>
      </div>

      <div class="form-group">
        <label for="amount">Expense Amount</label>
        <input
          type="number"
          :class="{ 'form-input-error': $v.expense.amount.$error }"
          data-test="expense-amount-input"
          id="amount"
          v-model="$v.expense.amount.$model"
        />
        <div v-if="$v.expense.amount.$error">
          <div
            class="form-feedback-error"
            v-if="!$v.expense.amount.required"
          >Expense amount is required.</div>
        </div>
      </div>

      <div class="form-group">
        <label for="paidBy">Paid By</label>
        <input
          type="text"
          :class="{ 'form-input-error': $v.expense.paidBy.$error }"
          data-test="expense-paidBy-input"
          id="paidBy"
          v-model="$v.expense.paidBy.$model"
        />

        <div v-if="$v.expense.paidBy.$error">
          <div class="form-feedback-error" v-if="!$v.expense.paidBy.required">Paid By is required.</div>
        </div>
      </div>

      <div class="form-group">
        <label for="date">Date</label>
        <input type="date" data-test="expense-date" id="expense-date" v-model="expense.date" />
      </div>

      <div class="form-group">
        <label for="splitters">Splitters</label>
        <input
          type="text"
          id="splitters"
          data-test="expense-splitters-input"
          v-model="frmSplitters"
        />
        <small id="splittersHelp" class="form-help">Comma separated e.g. p1-40, p2-60</small>
      </div>

      <button data-test="add-expense-button" type="submit">Add Expense</button>

      <div class="form-feedback-error" v-if="formHasErrors">Please correct the above errors</div>
    </form>
  </div>
</template>

<script>
import { required } from "vuelidate/lib/validators";

let expense = {};
expense = {
  description: "",
  amount: "",
  date: "",
  paidBy: "",
  split: "",
  splitters: ""
};

const axios = require("axios");

export default {
  name: "CreateExpense",
  data: function() {
    return {
      expense: expense,
      formHasErrors: false,
      frmSplitters: ""
    };
  },
  validations: {
    expense: {
      description: {
        required
        // minLength: minLength(4),
        // doesNotExist(value) {
        //     return !this.$store.getters.getProductBySlug(value);
        // }
      },
      amount: {
        required
      },
      paidBy: {
        required
      }
    }
  },
  watch: {
    "$v.$anyError": function() {
      this.formHasErrors = this.$v.$anyError;
    }
  },
  methods: {
    handleSubmit: function() {
      if (!this.formHasErrors) {

        //json object for splitters
        if (this.frmSplitters) {
          var splitterArray = [];
          var lsplitters = this.frmSplitters.split(",");
          lsplitters.forEach(splitter => {
            var person = splitter.split("-")[0];
            var percent = splitter.split("-")[1];
            splitterArray.push({
              pid: person,
              split: percent,
              splitType: "percent"
            });
          });
          expense.splitters = splitterArray;
          expense.split = "yes";
        }

        //calculate the expense id, this should be generated by the server in real world
        this.expense.id = this.$store.getters.getNextExpenseId;

        axios
          .post(
            "https://e28-expenser.firebaseio.com/expenses.json",
            this.expense
          )
          .then(response => {

            console.log(response);
            if (response.status == "200") {
              let key = response.data.description;
              this.$store.commit("addExpense", {
                [key]: this.expense
              });
            }

            expense = {
              description: "",
              amount: "",
              date: "",
              paidBy: "",
              split: "",
              splitters: ""
            };
            this.$router.push({
              name: "expenses"
            });
          });
      }
    }
  }
};
</script>

<style scoped>
</style>